<?php

use Illuminate\Database\Seeder;

class ServicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('services')->delete();
        
        \DB::table('services')->insert(array (
            0 => 
            array (
                'id' => 1,
                'place_id' => 3,
                'category_id' => 1,
                'category_secondary_id' => NULL,
                'name' => 'Reykjavik Campsite',
                'level_price' => NULL,
                'slug' => 'reykjavik-campsite',
            'introduction' => '<p>Du centre, suivre <strong>Borgart&uacute;n</strong> sur env 2 km ; le camping est sur la droite. Bus n&deg; 14 (arr&eacute;t: Laugardaslaug). Ouv de mi-mai &agrave; mi-sept. Env 1800-2 100 /SK/ pers (selon nombre de nuit&eacute;es), douche comprise. Cabanes (2-3 pers) 14 000 ISK.</p>',
            'details' => '<p>Camping de ville pelous&eacute; sans grand charme mais pratique et bien &eacute;quip&eacute; : vaste cuisine,barbecue, location de v&eacute;los, consigne et possibilit&eacute; d\'utiliser le cybercaf&eacute; et les lave-linge de l\'AJ attenante. C\'est une vraie usine, mais l\'accueil y est agr&eacute;able et les prestations de qualit&eacute;. Quelques modestes petits chalets cabins) avec lits superpos&eacute;s, 1 table et des chaises. Juste &agrave; c&ocirc;t&eacute;, la belle piscine de Laugardalslaug.</p>',
            'route' => 'Sundlaugavegur',
            'street_number' => '34',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '8 568-69-44',
            'lat' => '64.1467344000',
            'lng' => '-21.8827057000',
            'created_at' => '2018-01-30 15:35:07',
            'updated_at' => '2018-02-02 08:54:29',
        ),
        1 => 
        array (
            'id' => 2,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Reykjavik City Hostel',
            'level_price' => NULL,
            'slug' => 'reykjavik-city-hostel',
        'introduction' => '<p><span id="docs-internal-guid-53a6f4ed-4b73-3bdb-9f9c-0d2b2b70f374"><span style="font-size: 11pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Juste &agrave; c&ocirc;t&eacute; du camping . Ouv tte l\'ann&eacute;e. R&eacute;ception 8h-minuit. R&eacute;sa conseill&eacute;e bien &agrave; l\'avance. Lits en dortoir (4-6 lits) avec ou sans sdb 3 800-6500 ISK/pers; doubles 12 80015 300 ISK. R&eacute;duc avec la carte HI. Parking gratuit.</span></span></p>',
            'details' => '<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Une AJ moderne et agr&eacute;able, qui plus est d&eacute;tentrice du Nordic Ecolabel. Belles installations, notamment la salle commune avec livres et jeux, et nombreuses activit&eacute;s propos&eacute;es aux h&ocirc;tes (films, soir&eacute;es &agrave; theme, etc.). Possibilit&eacute; de r&eacute;server des excursions. Et, bien s&ucirc;r, tout l\'&eacute;quipement qu\'on peut attendre de ce genre d\'AJ:3 cuisines &eacute;quip&eacute;es, machines &agrave; laver, t&eacute;l&eacute;phones, consignes &agrave; bagages, location de v&eacute;los, etc.</span></p>',
            'route' => 'Sundlaugavegur',
            'street_number' => '34',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '8 553-81-10',
            'lat' => '64.1467344000',
            'lng' => '-21.8827057000',
            'created_at' => '2018-01-31 09:02:24',
            'updated_at' => '2018-02-02 08:55:59',
        ),
        2 => 
        array (
            'id' => 3,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Kex Hotel',
            'level_price' => NULL,
            'slug' => 'kex-hotel',
            'introduction' => '<p>Dortoirs 4-16 its <strong>4 900-8 900 ISK</strong>/ pers selon capacit&eacute; et saison.</p>
<p>Doubles (quelques-unes avec sdb) <strong>25 500 - 40 000 ISK</strong>.<br />D&eacute;licieux petit d&eacute;j-buffet, en sus.</p>',
        'details' => '<p><span id="docs-internal-guid-5c9b03da-4b77-5814-38ce-62aba8cdb065"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">A deux pas du centre. Install&eacute; dans une ancienne biscuiterie, avec d\'impressionnants volumes int&eacute;rieurs et une s&eacute;duisante organisation de l\'espace. Excellente literie et chambres assez spacieuses. Mobilier de r&eacute;cup. plein de clins d\'aeil au voyage dans un d&eacute;cor un poil d&eacute;jant&eacute;, coin salon-biblioth&egrave;que, bar sympa et grande terrasse au soleil. D&eacute;co des couloirs rigolote (pancartes lumineuses de bingo) et 2 cuisines &eacute;quip&eacute;es fort color&eacute;es. Immense caf&eacute;t&eacute;ria avec vue privil&eacute;gi&eacute;e sur la baie. On y sert une bonne petite restauration &agrave; prix mod&eacute;r&eacute;s. Personnel particuli&egrave;rement bienveillant. Vous nous avez compris, dans sa cat&eacute;gorie, c\'est notre adresse pr&eacute;f&eacute;r&eacute;e !</span></span></p>',
            'route' => 'Skúlagata',
            'street_number' => '28',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '561-60-60',
            'lat' => '64.1454786000',
            'lng' => '-21.9192661000',
            'created_at' => '2018-01-31 09:06:23',
            'updated_at' => '2018-02-02 08:58:16',
        ),
        3 => 
        array (
            'id' => 4,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Salvation Army Guesthouse',
            'level_price' => NULL,
            'slug' => 'salvation-army-guesthouse',
        'introduction' => '<p><span id="docs-internal-guid-5c9b03da-4b78-3795-2e24-601584ed4c19"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Ouv juin-ao&ucirc;t sit. Attention, h&eacute;bergement limit&eacute; &agrave; 1 nuit. Env 4 500 ISK/pers en dortoirs (non mixtes) avec sac de couchage et double sans sdb 15 500 ISK. Chambres priv&eacute;es 3-6 pers aussi.</span></span></p>',
            'details' => '<p>&nbsp;</p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt;"><span style="font-size: 12pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Cette grande batisse cr&egrave;me de l\'Arm&eacute;e du Salut, qui servait autrefois de logement pour les marins, est aujourd\'hui une r&eacute;sidence universitaire pendant l\'ann&eacute;e scolaire. Ce n\'est peut-&ecirc;tre pas l\'adresse la plus chaleureuse qui soit, mais elle a le m&eacute;rite d\'&ecirc;tre tr&egrave;s centrale, nette, et dispose de chambres convenables avec l\'acc&egrave;s &agrave; une cuisine &eacute;quip&eacute;e. C\'est l\'adresse la plus &eacute;conomique du centre de Reykjavik. Et messe a 10h30 ! </span></p>',
            'route' => 'Kirkjustræti',
            'street_number' => '2',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '56132-03',
            'lat' => '64.1471122000',
            'lng' => '-21.9415126000',
            'created_at' => '2018-01-31 09:08:01',
            'updated_at' => '2018-02-02 09:00:19',
        ),
        4 => 
        array (
            'id' => 5,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Reykjavik Downtown Hostel',
            'level_price' => NULL,
            'slug' => 'reykjavik-downtown-hostel',
        'introduction' => '<p><span id="docs-internal-guid-5c9b03da-4b79-9424-7577-b031fe85238d"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Ferme 3 jours &agrave; Noel. Dortoirs (4 ou 10 pers)</span></span></p>
<p><span id="docs-internal-guid-5c9b03da-4b79-9424-7577-b031fe85238d"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">6450-9 100 /SK/pers; <br />Doubles avec ou sans sdb 23 80027 800 ISK: petit d&eacute;j en sus. Reduc avec la carte HI. V </span></span></p>',
        'details' => '<p><span id="docs-internal-guid-5c9b03da-4b79-f624-f01f-a92a4538a703"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Une AJ confortable, impeccable et plut&ocirc;t coquette (meubles et parquet en bois clair). Agr&eacute;able caf&eacute; au rez-de-chauss&eacute;e et, dans une petite maison &agrave; l\'arri&egrave;re, une belle cuisine et des espaces communs de poche sous les toits. Machine &agrave; laver &agrave; dispo, consigne &agrave; bagages,</span></span><span style="background-color: transparent; font-family: Arial; font-size: 12pt; white-space: pre-wrap;">lockers, location de v&eacute;los. Le seul (gros) bemol : les prix qui, pour les doubles, se rapprochent de ceux d\'un hotel (reconnaissons, cependant, que le confort est &agrave; la hauteur).</span></p>',
            'route' => 'Vesturgata',
            'street_number' => '17',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '553-81-20',
            'lat' => '64.1496519000',
            'lng' => '-21.9439200000',
            'created_at' => '2018-01-31 09:10:12',
            'updated_at' => '2018-02-02 09:01:09',
        ),
        5 => 
        array (
            'id' => 6,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Loft',
            'level_price' => NULL,
            'slug' => 'loft',
        'introduction' => '<p><span id="docs-internal-guid-09ebb468-4b7b-8d20-f3d6-c37635a8a46c"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Reception 24h/24, tte l\'ann&eacute;e. Dortoirs (6-8 lits, avec sdb) 4 400-8 700 ISK/pers selon saison. Doubles avec sdb env 17 000 ISK. Petit d&eacute;j en sus. Reduc avec la carte HIV</span></span></p>',
        'details' => '<p><span id="docs-internal-guid-09ebb468-4b7b-a67f-416c-bc26ef64fe28"><span style="font-size: 12pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Une AJ install&eacute;e au beau milieu de la rue la plus commer&ccedil;ante de la ville (o&ugrave; les caf&eacute;s font un peu de bruit en fin de semaine...). Jolie deco dans l\'air du temps pour le bar, au der nier &eacute;tage, avec terrasse donnant sur les toits. Chambres doubles et dortoirs simples mais nickel.</span></span></p>',
            'route' => 'Bankastræti',
            'street_number' => '7a',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '553-81-40',
            'lat' => '64.1468440000',
            'lng' => '-21.9338339000',
            'created_at' => '2018-01-31 09:11:07',
            'updated_at' => '2018-02-02 09:01:53',
        ),
        6 => 
        array (
            'id' => 7,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => NULL,
            'name' => 'Snorri\'s Guesthouse',
            'level_price' => NULL,
            'slug' => 'snorris-guesthouse',
            'introduction' => '<p><span style="font-family: Arial; font-size: 14.6667px; white-space: pre-wrap;">Doubles sans ou avec sdb 18 600-24 500 ISK</span></p>',
            'details' => '<p><span style="font-family: Arial; font-size: 14.6667px; white-space: pre-wrap;">De l\'ext&eacute;rieur, assez banal. Pourtant, l\'int&eacute;rieur est nickel, frais et accueillant, certes au bord d\'une avenue passante, mais somme toute assez calme. Les 4 chambres d\'une jolie blancheur immacul&eacute;e, confortables, avec salle de bains et frigo, occupent la maison principale. Celles avec salles de bains communes, plus basiques mais toujours agr&eacute;ables, sont dans la maison voisine. Belle cuisine &eacute;quip&eacute;e &agrave; disposition, jardin reposant. Excellent accueil.</span></p>',
            'route' => 'Snorrabraut',
            'street_number' => '61',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '552-05-98',
            'lat' => '64.1394354000',
            'lng' => '-21.9199387000',
            'created_at' => '2018-01-31 09:16:50',
            'updated_at' => '2018-02-02 09:02:24',
        ),
        7 => 
        array (
            'id' => 8,
            'place_id' => 3,
            'category_id' => 1,
            'category_secondary_id' => 0,
            'name' => 'Brattagata Guesthouse',
            'level_price' => 1,
            'slug' => 'brattagata-guesthouse',
            'introduction' => '<p><span style="font-family: Arial; font-size: 14.6667px; white-space: pre-wrap;"> Doubles 15 00020 000 I&Scaron;K selon saison. Parking gratuit.</span></p>',
            'details' => '<p><span style="font-family: Arial; font-size: 14.6667px; white-space: pre-wrap;">Presque id&eacute;alement situ&eacute;e dans une petite rue tranquille de la vieille ville et dans une maison pimpante aux murs en t&ocirc;le rouge, typique du quartier. Chambres vraiment mignonnes avec meubles anciens. Cuisine et buanderie &agrave; dispo. Joli petit d&eacute;j et accueil aux petits soins.</span></p>',
            'route' => 'Mjóstræti',
            'street_number' => NULL,
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '612-98-00',
            'lat' => '64.1486448000',
            'lng' => '-21.9429478000',
            'created_at' => '2018-01-31 09:19:00',
            'updated_at' => '2018-02-05 11:55:40',
        ),
        8 => 
        array (
            'id' => 9,
            'place_id' => 4,
            'category_id' => 1,
            'category_secondary_id' => 2,
            'name' => 'Test',
            'level_price' => 1,
            'slug' => 'test',
            'introduction' => '<p>sdd</p>',
            'details' => '<p>dss</p>',
            'route' => NULL,
            'street_number' => NULL,
            'locality' => 'Paris',
            'country' => 'France',
            'phone' => NULL,
            'lat' => '48.8566140000',
            'lng' => '2.3522219000',
            'created_at' => '2018-02-03 09:48:12',
            'updated_at' => '2018-02-03 09:48:12',
        ),
        9 => 
        array (
            'id' => 10,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 2,
            'name' => 'Brjarins Beztu',
            'level_price' => 1,
            'slug' => 'brjarins-beztu',
            'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; white-space: pre-wrap;">TIJ 10h-Oh30. </span></p>
<p><span style="font-family: Arial; font-size: 12px; text-align: justify; white-space: pre-wrap;">Environ 420 ISK pour un hot-dog. </span></p>',
            'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; white-space: pre-wrap;">De son nom complet B&aelig;jarins Beztu Pisur, litt&eacute;ralement les meilleures SaulCisses de la ville, c\'est LE kiosque a hot-dogs de la capitale! On s\'y presse &agrave; toute heure du jour, pour s\'offrir un hot-dog a divorSUS SUOS et aux petits oignons frits. Grosse table et bancs dehors. M&ecirc;me Bill Clinton y est pass&eacute;, et il s\'y connait en gastronomie!</span></p>',
            'route' => 'Hafnarstræti',
            'street_number' => '17',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => NULL,
            'lat' => '64.1483519000',
            'lng' => '-21.9398990000',
            'created_at' => '2018-02-03 13:29:28',
            'updated_at' => '2018-02-03 13:29:28',
        ),
        10 => 
        array (
            'id' => 11,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 0,
            'name' => 'Hamborgarabülla TomaSar',
            'level_price' => 1,
            'slug' => 'hamborgarabulla-tomasar',
            'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; white-space: pre-wrap;">Tous les jours 11h30-21h. Burgers 1 000-2 600 ISK.</span></p>',
            'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; white-space: pre-wrap;">Sur le port, dans une toute petite maiSon un peu Art d&eacute;co, rigolote avec sa fa&ccedil;ade arrondie, surmont&eacute;e d\'une horloge. Un repaire de hamburgers old school, bien gras et succulents! Atmosph&egrave;re tr&egrave;s relax, frites Croustillantes. Longues tables dehors. On en redemande. Et on n\'est pas les seuls puisque la maison a ouvert quelques annexes sur l\'&icirc;le et jusqu\'&agrave; Londres ou Berlin. Burgers vegetariens, au cas o&ugrave;.</span></p>',
            'route' => 'Geirsgata',
            'street_number' => NULL,
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => NULL,
            'lat' => '64.1494546000',
            'lng' => '-21.9396023000',
            'created_at' => '2018-02-03 13:37:02',
            'updated_at' => '2018-02-03 13:37:02',
        ),
        11 => 
        array (
            'id' => 12,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 0,
            'name' => 'Sandholt',
            'level_price' => 1,
            'slug' => 'sandholt',
            'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; text-indent: 11.2px; white-space: pre-wrap;">Petit d&eacute;j 620-1700 ISK. Sandwichs 900-1300 ISK.</span></p>',
        'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; text-indent: 11.2px; white-space: pre-wrap;"> Consid&eacute;r&eacute;e - &agrave; juste titre! - comme la meilleure boulangerie de la ville. Excellent accueil (en fran&ccedil;ais, parfois) et agr&eacute;able petite salle discr&egrave;tement design pour de go&Uuml;teux sandwichs et de roboratifs petits d&eacute;jeuners.</span></p>',
            'route' => 'Laugavegur',
            'street_number' => '36',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '8 55-35-24',
            'lat' => '64.1450763000',
            'lng' => '-21.9263057000',
            'created_at' => '2018-02-03 13:37:45',
            'updated_at' => '2018-02-03 13:37:45',
        ),
        12 => 
        array (
            'id' => 13,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 0,
            'name' => 'Seabaron Segreifinn',
            'level_price' => 1,
            'slug' => 'seabaron-segreifinn',
            'introduction' => '<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt;"><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"> 11h30-22h 23h en ete </span></p>
<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt;"><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Brochettes </span><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">1900-2 000 ISK.</span></p>
<p>&nbsp;</p>',
            'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 5.44px; white-space: pre-wrap;"> Une bicoque de p&ecirc;cheur verte sur le port. Apr&egrave;s avoir franchi une petite terrasse abrit&eacute;e du vent par des vitres en plexi= glas, on entre dans une gargote aussi minuscule que nustique, charg&eacute;e de dessins et photos &eacute;voquant la p&eacute;che en Islande. Tables d&eacute;coup&eacute;es dans des troncs d\'arbre et tonnelets &agrave; poissons en guise de si&egrave;ges. Dans cette pittoresque adresse ouverte par un ancien pocheur, les produits de la mer sont &eacute;videmment &agrave; l\'honneur. De d&euml;llicieuses brochettes de langouste, de fl&eacute;tan, de truite de ma, de Humon.. Tres populaire aussi pour sa bisque de homard. On choisit dans le frigo, on Commande au comptoir et, quand c\'est pr&eacute;t, on &eacute;change Son petit ticket jaune Contre un plat.</span></p>',
            'route' => 'Geirsgata',
            'street_number' => '8',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '553-15-00',
            'lat' => '64.1505357000',
            'lng' => '-21.9439663000',
            'created_at' => '2018-02-03 13:40:31',
            'updated_at' => '2018-02-03 13:40:31',
        ),
        13 => 
        array (
            'id' => 14,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 0,
            'name' => 'Ostabudin',
            'level_price' => 1,
            'slug' => 'ostabudin',
        'introduction' => '<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt; text-indent: 4.08pt;"><span style="font-size: 9pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> Lun-ven 10-18h, Sam Tih-16h. Poison du jour (</span><span style="font-size: 9pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">midi) 1 200 ISK. Plats 3200-3900 ISK.</span></p>
<p>&nbsp;</p>',
        'details' => '<p><span style="font-family: Arial; font-size: 12px; white-space: pre-wrap;">C\'est le meilleur fromager de la ville, dot&eacute; d\'un riche rayon &eacute;picerie fine et de go&ucirc;teux produits maison comme l\'oie ou le guillemot fumes. Mais le </span><span style="font-family: Arial;"><span style="font-size: 12px; white-space: pre-wrap;">vrai secret de cette adresse se cache au sous-sol. Au d&eacute;jeuner, uniquement, les employ&eacute;s du coin (et pas mal de touristes) se r&eacute;galent du poisson du jour d\'une belle fraicheur, &agrave; un prix fort d&eacute;mocratique ou d\'un plat chaud elaborb, aSSEZ cher quant &agrave; lui.</span></span></p>',
            'route' => 'Skólavörðustígur',
            'street_number' => '8',
            'locality' => 'Reykjavík',
            'country' => 'Islande',
            'phone' => '562-27-72',
            'lat' => '64.1456328000',
            'lng' => '-21.9319990000',
            'created_at' => '2018-02-03 13:43:14',
            'updated_at' => '2018-02-03 13:43:14',
        ),
        14 => 
        array (
            'id' => 15,
            'place_id' => 3,
            'category_id' => 5,
            'category_secondary_id' => 0,
            'name' => 'Kryddlegin Hjörtu',
            'level_price' => 1,
            'slug' => 'kryddlegin-hjortu',
        'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Lun-Sam 11h30-21h 23h Perl-3m), din 17h-22h.</span></p>',
    'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Au d&eacute;j, buffer-salades 1 890 ISK Ou plat du jour 2690 ISK: sinon, 2900-3500 ISK. La d&eacute;co &eacute;voque un s&eacute;jour au Maghreb. Et la Cuisine se teinte parfois aussi d\'exOtisme (avec facOS, fajitas...) dans cet accueillant restaurant v&eacute;g&eacute;tarien. Beau buffet de Soupes et de salades qui, pour la ville, est un vrai bon plan au d&eacute;jeuner.</span></p>',
        'route' => 'Hverfisgata',
        'street_number' => '33',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '588-88-18',
        'lat' => '64.1465808000',
        'lng' => '-21.9292277000',
        'created_at' => '2018-02-03 13:44:18',
        'updated_at' => '2018-02-03 13:44:18',
    ),
    15 => 
    array (
        'id' => 16,
        'place_id' => 3,
        'category_id' => 5,
        'category_secondary_id' => 0,
        'name' => 'Islenski Barinn',
        'level_price' => 1,
        'slug' => 'islenski-barinn',
    'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Tlj11h30-22h (Minuit ven-sam). </span></p>
<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Plats environ 2500-3 000 ISK.</span></p>',
    'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Bonne id&eacute;e que ce bistrot islandais d&eacute;cor&eacute; comme un appartement (papier peint &agrave; l\'ancienne et meubles en bois ou r&eacute;tro, dans des tons bleu turquoise) o&ugrave; l\'on peut accompagner de petits plats typiquement locaux une bonne s&eacute;lection de bi&egrave;res tout aussi locales. Pour les petits budgets, hot-dogs et burgers avec un soup&ccedil;on d\'id&eacute;e. Ambiance de bar plus que de resto, super accueil et service &agrave; la fois pro et chaleureux.</span></p>',
        'route' => 'Pósthússtræti',
        'street_number' => '9',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '517-67-67',
        'lat' => '64.1477330000',
        'lng' => '-21.9385023000',
        'created_at' => '2018-02-03 13:46:40',
        'updated_at' => '2018-02-03 13:46:40',
    ),
    16 => 
    array (
        'id' => 17,
        'place_id' => 3,
        'category_id' => 5,
        'category_secondary_id' => 0,
        'name' => 'Glo',
        'level_price' => 1,
        'slug' => 'glo',
        'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;"> A l\'angle de Klapparstigur, &agrave; l\'&eacute;tage. Ty 11-21h. Plats 1 900-2200 ISK</span></p>',
    'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">Le meilleur resto v&eacute;g&eacute;tarien de la ville (et du pays, dit-on !). Cadre joliment design (avec mur en rondins de bois pour la couleur locale) et d&eacute;licieux Veggie burgers, chili - sans Carnes, Sushis v&eacute;g&eacute;tariens, soupes parfum&eacute;es, belles salades Compos&eacute;es, pizzas... de délicieuses petites pommes de terme au tour et de Sauces originales et parfumées (Tartarë, Coriandre et citron vert, Coconut curry, miel et moutarde, etc.), en Supplément... Les amateurs de verdure se rabattront sur les bonnes petites salades du buffet. L\'endroit idéal pour un repas simple, frais et goûteux, où les produits locaux ont la part belle. En primo, un accueil particulièrement affable. Vernir de bonne heure, on y est vite comme des Sardines en boite ! </span></p>',
        'route' => 'Laugavegur',
        'street_number' => '20b',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '553-11-11',
        'lat' => '64.1457312000',
        'lng' => '-21.9294195000',
        'created_at' => '2018-02-03 13:48:12',
        'updated_at' => '2018-02-03 13:48:12',
    ),
    17 => 
    array (
        'id' => 18,
        'place_id' => 3,
        'category_id' => 5,
        'category_secondary_id' => 0,
        'name' => 'Eld\'s Sidjan',
        'level_price' => 1,
        'slug' => 'elds-sidjan',
    'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Tlj 11-23h. Pizzas environ 1 500-3 500 ISK selon taille 3 diff&eacute;rentes).</span></p>',
'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">C\'est l\'une des 3 adresses de cette chaine locale de pizzerias, un peu &agrave; l\'&eacute;cart du centre, dans un quartier residentiel tranquille. Une pizzeria sur 3 &eacute;tages (fourneaux &agrave; l\'entresol et petites salles au-dessus) ayant la particularit&eacute; de servir des pizZ&auml;s cuites au feu de bois de bouleau islandais. Une trentaine au choix, &agrave; la pate fine et COUstillante, pl&eacute;biscit&eacute;es par les Reykjavikiens. </span></p>',
    'route' => 'Bragagata',
    'street_number' => '38',
    'locality' => 'Reykjavík',
    'country' => 'Islande',
    'phone' => '562-38-38',
    'lat' => '64.1423163000',
    'lng' => '-21.9311675000',
    'created_at' => '2018-02-03 13:51:00',
    'updated_at' => '2018-02-03 13:51:00',
),
18 => 
array (
    'id' => 19,
    'place_id' => 3,
    'category_id' => 5,
    'category_secondary_id' => 0,
    'name' => 'Kaffivagninn',
    'level_price' => 1,
    'slug' => 'kaffivagninn',
'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 1.6px; white-space: pre-wrap;">Tlj 8h-18h le week-end a partir de 10h). Plats avec Soupe et cafe) 2300-2900 /SK. </span></p>',
'details' => '<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt; text-indent: 1.2pt;"><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Grande salle vitr&eacute;e et terrasse largement ouvertes sur le port, frequent&eacute;es par des p&eacute;cheurs </span><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">mais aussi par les terriens qui ont eu l\'heureuse id&eacute;e de venir s\'&eacute;garer par ici ! Des salades, mais aussi beaucoup de poissons (tartins de Crevettes, Saumon..-) d\'une &eacute;clatante fraicheur. Du tr&egrave;s classique, plut&ocirc;t bon, et l\'accueil est tr&egrave;s gentil.</span></p>
<p>&nbsp;</p>',
'route' => 'Grandagarður',
'street_number' => NULL,
'locality' => 'Reykjavík',
'country' => 'Islande',
'phone' => '551-5932',
'lat' => '64.1545183000',
'lng' => '-21.9451234000',
'created_at' => '2018-02-03 13:52:50',
'updated_at' => '2018-02-03 13:52:50',
),
19 => 
array (
'id' => 20,
'place_id' => 3,
'category_id' => 5,
'category_secondary_id' => 0,
'name' => 'Shalimar',
'level_price' => 1,
'slug' => 'shalimar',
'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: justify; text-indent: 3.2px; white-space: pre-wrap;">TIJ 11h30-(16h sam-dim )23h . Piats env 1700-2600 ISK.</span></p>',
'details' => '<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 5pt; text-indent: 2.4pt; text-align: justify;"><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Envie d\'une petite escapade exotique ? Ce resto de poche sur 2 &eacute;tages Servant une excellente cuisine indo-pakistanaise est pour vous. Box confortables avec banquettes ou tables bien s&eacute;par&eacute;es. Si Vous avez le palais Sensible et tenez a appr&eacute;cier le repas, demander a mwild, car c\'est relev&eacute;! Service un peu long </span><span style="font-size: 9pt; font-family: Arial; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">mals sympathique. </span></p>
<p>&nbsp;</p>',
'route' => 'Austurstræti',
'street_number' => '4',
'locality' => 'Reykjavík',
'country' => 'Islande',
'phone' => '551-02-92',
'lat' => '64.1475328000',
'lng' => '-21.9382232000',
'created_at' => '2018-02-03 13:54:02',
'updated_at' => '2018-02-03 13:54:02',
),
20 => 
array (
'id' => 21,
'place_id' => 3,
'category_id' => 1,
'category_secondary_id' => 0,
'name' => 'Hornið',
'level_price' => 2,
'slug' => 'hornid',
'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">TlJ 11h23h30. R&eacute;sa Conseil&eacute;e. Pales et pizzas 2300-3 000 ISK</span></p>',
'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">Un classique. Cadre clair et plaisant avec baile vitr&eacute;e et tables ondes en marbre dans la salle &agrave; l\'entr&eacute;e, baie vitre encore mais des tables cam&eacute;es en bois &agrave; l\'arri&egrave;re. Bonne cuisine d\'inspiration italienne, enrichie de quelques touches plus locales (saumon au four, morue risotto sauce yaourt et menthej. Une bonne adresse pour les gros estomacs. Et &ccedil;a fait une bonne trentaine d\'ann&eacute;es que &ccedil;a dure ! </span></p>',
    'route' => 'Hafnarstræti',
    'street_number' => '15',
    'locality' => 'Reykjavík',
    'country' => 'Islande',
    'phone' => '551-33-40',
    'lat' => '64.1479236000',
    'lng' => '-21.9372928000',
    'created_at' => '2018-02-03 13:55:17',
    'updated_at' => '2018-02-03 13:55:17',
),
21 => 
array (
    'id' => 22,
    'place_id' => 3,
    'category_id' => 5,
    'category_secondary_id' => 0,
    'name' => 'Tapas Barinn',
    'level_price' => 2,
    'slug' => 'tapas-barinn',
'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">TIJ 17h30-23h30 (1h30 ven-sam: Une raret&eacute; a Reykjavik I). R&eacute;sa conseill&eacute;</span></p>
<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">Tapas 2 000-3 000 ISK. Menus 7200-9500 ISK</span></p>',
    'details' => '<p><span style="font-family: Arial; font-size: 12px; text-align: right; white-space: pre-wrap;">Ambiance souvent &agrave; la fete, d&eacute;co a l\'andalouse pour r&eacute;viser le verbe - taper : des Serveuses qui tapent dans leurs mains comme des danseuses de flamenco pour annoncer l\'arriv&eacute;e des tapas. En v&eacute;rit&eacute;, de vrais plats, &agrave; la fois subtils et geringereux et sign&eacute;s par un chef qui tape dans les classiques islandais et les revisite joliment (macareum, homard... Un barinn o&ugrave; l\'on se tape la cloche.</span></p>',
        'route' => 'Vesturgata',
        'street_number' => '36',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '551-23-44',
        'lat' => '64.1504936000',
        'lng' => '-21.9473812000',
        'created_at' => '2018-02-03 13:57:11',
        'updated_at' => '2018-02-03 13:57:11',
    ),
    22 => 
    array (
        'id' => 23,
        'place_id' => 3,
        'category_id' => 5,
        'category_secondary_id' => 0,
        'name' => 'Cafe Loki',
        'level_price' => 2,
        'slug' => 'cafe-loki',
    'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 16px; white-space: pre-wrap;">Tlj 9h (11h dim)-21h. Juste en face de l\'&eacute;glise Hallgrimskirkja. </span></p>
<p><span style="font-family: Arial; font-size: 12px; text-indent: 16px; white-space: pre-wrap;">Tarines 800-2 050 ISK plats 2200-3 000 ISK.</span></p>',
        'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 16px; white-space: pre-wrap;">Genre cat&eacute;t proprette avec vue sur l\'&eacute;glise, o&ugrave; l\'on peut d&eacute;guster d\'authentiques sp&eacute;cialit&eacute;s islandaises, dont le requin ferment&eacute; , r&eacute;alis&eacute;es &agrave; partir de tres bons produits. Leur pain maison est absolument unique. D&eacute;licieuse soupe de poisson, </span></p>',
        'route' => 'Lokastígur',
        'street_number' => '28a',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '466-28-28',
        'lat' => '64.1424558000',
        'lng' => '-21.9288922000',
        'created_at' => '2018-02-03 13:58:19',
        'updated_at' => '2018-02-03 13:58:19',
    ),
    23 => 
    array (
        'id' => 24,
        'place_id' => 3,
        'category_id' => 5,
        'category_secondary_id' => 0,
        'name' => 'Laundromaat Cale',
        'level_price' => 2,
        'slug' => 'laundromaat-cale',
    'introduction' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 16px; white-space: pre-wrap;">TIJ 8h (9h Weekend)-23h (Minuit jeu-Sam). Burgers 2500-2 700 ISK,</span></p>',
    'details' => '<p><span style="font-family: Arial; font-size: 12px; text-indent: 16px; white-space: pre-wrap;"> İnstall&eacute;e dans un beau b&acirc;timent frapp&eacute; d\'une &eacute;toile de David, Sympathiqu&euml; caf&eacute;t&eacute;rialaverie particuli&egrave;rement accueillante pour les familles (avec salle de jeux pour les enfants). D&eacute;cor de vieilles Cartes de g&eacute;ographie, affiches, original Comptoir-biblioth&egrave;que au Centre, machines &agrave; laver au sous-sol..</span></p>',
        'route' => 'Austurstræti',
        'street_number' => '9',
        'locality' => 'Reykjavík',
        'country' => 'Islande',
        'phone' => '587-75-55',
        'lat' => '64.1475303000',
        'lng' => '-21.9382063000',
        'created_at' => '2018-02-03 13:59:51',
        'updated_at' => '2018-02-03 13:59:51',
    ),
    24 => 
    array (
        'id' => 26,
        'place_id' => 3,
        'category_id' => 6,
        'category_secondary_id' => 0,
        'name' => 'test2',
        'level_price' => 1,
        'slug' => 'test2',
        'introduction' => '<p>sqsq</p>',
        'details' => '<p>sqsq</p>',
        'route' => NULL,
        'street_number' => NULL,
        'locality' => 'Reykjavik',
        'country' => 'Islande',
        'phone' => NULL,
        'lat' => '64.1265206000',
        'lng' => '-21.8174392000',
        'created_at' => '2018-02-05 10:00:55',
        'updated_at' => '2018-02-05 10:00:55',
    ),
    25 => 
    array (
        'id' => 27,
        'place_id' => 3,
        'category_id' => 6,
        'category_secondary_id' => 0,
        'name' => 'Mon test',
        'level_price' => 1,
        'slug' => 'mon-test',
        'introduction' => '<p>qsq</p>',
        'details' => '<p>sqs</p>',
        'route' => NULL,
        'street_number' => NULL,
        'locality' => 'Reykjavik',
        'country' => 'Islande',
        'phone' => NULL,
        'lat' => '64.1265206000',
        'lng' => '-21.8174392000',
        'created_at' => '2018-02-05 10:02:05',
        'updated_at' => '2018-02-05 10:02:05',
    ),
));
        
        
    }
}